"""add templates, scheduled_items, logs tables

Revision ID: 29185d1ea547
Revises: 5260cb01b807
Create Date: 2026-03-29 21:49:35.692597
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29185d1ea547'
down_revision: Union[str, None] = '5260cb01b807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cipp_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cipp_logs_created_at'), 'cipp_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_cipp_logs_tenant_id'), 'cipp_logs', ['tenant_id'], unique=False)
    op.create_table('cipp_scheduled_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('schedule', sa.String(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cipp_scheduled_items_type'), 'cipp_scheduled_items', ['type'], unique=False)
    op.create_table('cipp_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cipp_templates_type'), 'cipp_templates', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cipp_templates_type'), table_name='cipp_templates')
    op.drop_table('cipp_templates')
    op.drop_index(op.f('ix_cipp_scheduled_items_type'), table_name='cipp_scheduled_items')
    op.drop_table('cipp_scheduled_items')
    op.drop_index(op.f('ix_cipp_logs_tenant_id'), table_name='cipp_logs')
    op.drop_index(op.f('ix_cipp_logs_created_at'), table_name='cipp_logs')
    op.drop_table('cipp_logs')
    # ### end Alembic commands ###
